import { Button, ScrollView, StandardButton } from "std-widgets.slint";

export struct UiUserMessageData {
    name: string,
    content: string
}
export component UiUserMessage {
    in property <UiUserMessageData> data;

    x: 25px;
    width: 450px;
    height: name.height + content.height;

    name := Text {
        y: 0px;
        width: parent.width;
        text: data.name;
        font-size: 24px;
        horizontal-alignment: left;
    }
    content := Text {
        y: 35px;
        width: parent.width;
        text: data.content;
        font-size: 16px;
        horizontal-alignment: left;
        wrap: word-wrap;
    }
}
export struct UiRoomData {
    name: string,
    id: string,
}
export component ClientUIRoom {
    height: 100px;
    width: 315px;

    in property <UiRoomData> data;

    callback join(string);
    callback remove(string);

    // Background
    Rectangle {
        x: 0px;
        y: 0px;
        width: 200px;
        height: 100px;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }

    // Name
    Text {
        x: 10px;
        y: 5px;
        text: data.name;
        font-size: 24px;
        width: 185px;
        wrap: word-wrap;
    }

    // ID
    Text {
        x: 10px;
        y: 80px;
        text: "ID: " + data.id;
        font-size: 12px;
        width: 200px;
        wrap: word-wrap;
    }

    // Join button
    Rectangle {
        x: join_button.x;
        y: join_button.y;
        width: join_button.width;
        height: join_button.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    Text {
        x: join_button.x + 25px;
        y: join_button.y + 5px;
        text: "Join";
        font-size: 24px;
    }
    join_button := Button {
        x: 215px;
        y: 0px;
        width: 100px;
        height: 45px;
        opacity: 0;     
        clicked => {
            join(data.id);
        }
    }

    // Remove button
    Rectangle {
        x: remove_button.x;
        y: remove_button.y;
        width: remove_button.width;
        height: remove_button.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    Text {
        x: remove_button.x + 5px;
        y: remove_button.y + 5px;
        text: "Remove";
        font-size: 24px;
    }
    remove_button := Button {
        x: 215px;
        y: 55px;
        width: 100px;
        height: 45px;
        opacity: 0;     
        clicked => {
            remove(data.id);
        }
    }
}
export component ServerTicket {
    callback set-server-ticket(string);

    // Background
    Rectangle {
        x: 0px;
        y: 0px;
        width: 400px;
        height: 175px;
        border-radius: 15px;
        background: rgb(35, 35, 35);
    }

    Text {
        x: 30px;
        y: 15px;
        text: "Server ticket";
        font-size: 32px;
    }

    Text {
        x: 30px;
        y: 75px;
        text: "Input server ticket. THIS MUST BE SET!";
        font-size: 16px;
    }

    // Input field
    input_rect := Rectangle {
        x: 15px;
        y: 110px;
        width: 360px;
        height: 50px;
        border-radius: 15px;
        background: rgb(50, 50, 50);
    }
    input_field := TextInput {
        x: input_rect.x + 15px;
        y: input_rect.y;
        width: input_rect.width;
        height: input_rect.height;
        font-size: 32px;
        edited => {set-server-ticket(self.text)}
    }
}
export component AddRoom {
    callback add-room(string);

    // Background
    Rectangle {
        x: 0px;
        y: 0px;
        width: 400px;
        height: 175px;
        border-radius: 15px;
        background: rgb(35, 35, 35);
    }

    Text {
        x: 30px;
        y: 15px;
        text: "Add room";
        font-size: 32px;
    }

    Text {
        x: 30px;
        y: 75px;
        text: "Input room ID";
        font-size: 16px;
    }

    // Input field
    input_rect := Rectangle {
        x: 15px;
        y: 110px;
        width: 270px;
        height: 50px;
        border-radius: 15px;
        background: rgb(50, 50, 50);
    }
    input_field := TextInput {
        x: input_rect.x + 15px;
        y: input_rect.y;
        width: input_rect.width;
        height: input_rect.height;
        font-size: 32px;
    }

    // Join button
    Rectangle {
        x: create_button.x + 25px;
        y: create_button.y + 25px;
        width: create_button.width;
        height: create_button.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    Text {
        x: create_button.x + 35px;
        y: create_button.y + 25px;
        text: "Add";
        font-size: 32px;
    }
    create_button := Button {
        x: 275px;
        y: 85px;
        width: 85px;
        height: input_rect.height;
        opacity: 0;     
        clicked => {
            add-room(input_field.text);
            input_field.text = "";
        }
    }
}
export component ClientMenu {
    width: 800px;
    height: 600px;

    callback set-server-ticket(string);
    callback join-room(string);
    callback add-room(string);
    callback remove-room(string);

    in property <[UiRoomData]> rooms;

    ServerTicket {
        x: 15px;
        y: 15px;
        set-server-ticket(addr) => {set-server-ticket(addr)}
    }

    AddRoom {
        x: 15px;
        y: 212px;
        add-room(id) => {add-room(id)}
    }

    Text {
        x: 30px;
        y: 430px;
        width: 375px;
        text: "If you'd like to create a room instead, run the server executable and continue from here.";
        font-size: 24px;
        wrap: word-wrap;
    }

    // Rooms
    Rectangle {
        x: 430px;
        y: 15px;
        width: 345px;
        height: 570px;
        border-radius: 15px;
        background: rgb(35, 35, 35);
    }

    Text {
        x: 460px;
        y: 25px;
        text: "Rooms";
        font-size: 32px;
    }

    ScrollView {
        x: 445px;
        y: 75px;
        height: 510px;

        VerticalLayout {
            spacing: 15px;

            for room in rooms: ClientUIRoom {
                data: room;
                join(id) => {join-room(id)}
                remove(id) => {remove-room(id)}
            }
        }
    }
}
export component ChatView {
    width: 800px;
    height: 600px;

    callback back();
    callback send(string);

    in property <string> room-name;
    in property <[UiUserMessageData]> messages;

    // Top panel
    Rectangle {
        y: 0px;
        width: 100%;
        height: 50px;
        background: rgb(35, 35, 35);
    }

    Text {
        y: 0px;
        text: room-name;
        horizontal-alignment: left;
        vertical-alignment: center;
        font-size: 32px;
    }

    // Back button
    Rectangle {
        x: back_button.x;
        y: back_button.y;
        width: back_button.width;
        height: back_button.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    Text {
        x: back_button.x + 20px;
        y: back_button.y;
        text: "Back";
        font-size: 28px;
    }
    back_button := Button {
        x: 15px;
        y: 5px;
        width: 100px;
        height: 40px;
        opacity: 0;     
        clicked => {
            back();
            input_field.text = "";
        }
    }

    // Bottom panel
    Rectangle {
        y: 525px;
        width: 100%;
        height: 75px;
        background: rgb(35, 35, 35);
    }

    ScrollView {
        y: 50px;
        height: 475px;

        VerticalLayout {
            spacing: 15px;

            for message in messages : UiUserMessage {
                data: message;
            }
        }
    } 

    // Input area
    input_rect := Rectangle {
        x: 10px;
        y: 540px;
        width: 650px;
        height: input_field.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    input_field := TextInput {
        x: 25px;
        y: 550px;
        width: 625px;
        height: 50px;
        font-size: self.height / 2.5;
        wrap: word-wrap;
        cursor-position-changed(position) => {
            //
        }
    }

    // Send button
    Rectangle {
        x: send_button.x;
        y: send_button.y;
        width: send_button.width;
        height: send_button.height;
        background: rgb(50, 50, 50);
        border-radius: 15px;
    }
    Text {
        x: send_button.x + 25px;
        y: send_button.y;
        text: "Send";
        font-size: 32px;
    }
    send_button := Button {
        x: 670px;
        y: input_rect.y;
        width: 120px;
        height: input_field.height;
        opacity: 0;     
        clicked => {
            send(input_field.text);
            input_field.text = "";
        }
    }
}