import { UiRoomData, UiUserMessageData, UiUserMessage, ClientMenu, ChatView } from "client-ui.slint";
import { ServerMenu } from "server-ui.slint";

export component ClientWindow inherits Window {
    width: 800px;
    height: 600px;

    private property <bool> main-menu-visible;
    private property <bool> chat-view-visible;

    in property <[UiRoomData]> rooms;
    in-out property <string> room-name;
    in-out property <[UiUserMessageData]> messages;

    callback send-message(string);
    callback chat-view-back();
    callback set-user-name(string);
    callback set-server-ticket(string);
    callback add-room(string);
    callback remove-room(string);
    callback join-room(string);

    callback main-menu();
    callback chat-view();

    init => { 
        main-menu()
    }

    main-menu => {
        main-menu-visible = true;
        chat-view-visible = false;
        room-name = "";
        messages = [];
    }

    chat-view => {
        main-menu-visible = false;
        chat-view-visible = true;
    }

    ClientMenu {
        rooms: rooms;
        visible: main-menu-visible;
        set-user-name(name) => {set-user-name(name)}
        set-server-ticket(addr) => {set-server-ticket(addr)}
        add-room(id) => {add-room(id)}
        remove-room(id) => {remove-room(id)}
        join-room(id) => {join-room(id)}
    }
    ChatView {
        visible: chat-view-visible;
        room-name: room-name;
        messages: messages;
        
        send(content) => {send-message(content)}
        back => {main-menu(); chat-view-back()}
    }
}
export component ServerWindow inherits Window {
    width: 800px;
    height: 600px;

    in property <string> ticket;
    in property <[UiRoomData]> rooms;

    callback create-room(string);
    callback delete-room(string);
    callback copy-ticket(string);

    ServerMenu {
        ticket: ticket;
        rooms: rooms;
        create-room(name) => {create-room(name)}
        delete-room(id) => {delete-room(id)}
        copy-ticket(ticket) => {copy-ticket(ticket)}
    }
}
export component OfflineServerAddrDialog inherits Dialog {
    Text {
        text: "This server address is currently offline!";
        font-size: 32px;
        width: 400px;
        wrap: word-wrap;
    }
}
export component TicketCopyFailure inherits Dialog {
    Text {
        text: "Failed to copy the ticket!";
        font-size: 32px;
        width: 400px;
        wrap: word-wrap;
    }
}